flow:
  h_init: 0.0
  Ch_w: 10.0e-4 #1.0e-7 #
  h_w: 0.01
  alpha: 0.4 #Courant
  Cf: 0.003
  g: 9.81
  R: 1.65
  lambda_p: 0.7 #porosity
  r0: 1.5 #1.5 #can calc
  nu: 1.763e-6 #1.5℃ saltwater　1.010e-6(20℃)
  kappa: 0.05 # to stabilize?
  nu_a: 0.75 # to stabilize?
  implicit_num: 100
  implicit_threshold: 1.0e-8
  C_init: 0.0
  gamma: 0.35
  la: 0.1 #can obtain from emprical formula (Parker 1982)
  water_entrainment: True
  ewc: 0.8 #def=1
  water_detrainment: True
  det_factor: 1 #3.05
  suspension: True
  bedload_transport: False
  sed_entrainment_func: NRv2 #Traer2012 #NRv1 # #GP1991field #GP1991exp #wright_and_parker(2004) #Leeuw2020P2 #
  p_coef: 1
  camax: 0.05 #def=0.3
  no_erosion: False #True #
  no_erosion_Ds: [] #[0,1]
  dt_local_limit: 5.0
  model: 3eq
  salt: False
  alpha_TKE: 0.1
  karman: 0.4
  duration: 0

grid:
  length: 6000
  width: 2000
  spacing: 10
  slope_outside: 0.2
  slope_inside: 0.05
  slope_basin: 0.05
  slope_basin_break: 2000
  canyon_basin_break: 2200
  canyon_center: 1000
  canyon_half_width: 100
  canyon: canyon
  noise: 0.0
